spring:
  datasource:
    url: jdbc:mysql://124.71.149.35:3306/uyou?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
server:
  port: 8080
mybatis:
  type-aliases-package: com.uyou.entity
  mapper-locations: classpath:mybatis/mapper/*.xml,classpath:mybatis/helperMapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
jasypt:
  encryptor:
    password: WwDih=dDq)
