spring:
  datasource:
    url: jdbc:mysql://172.19.240.201:3306/uyou?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ENC(iw69MoykgsZ7cklWmtUZikZpoltmkMh5fdc546SP2C6KoyVMT4v6UO0g7KH1RQGq)
server:
  port: 8080
mybatis:
  type-aliases-package: com.uyou.entity
  mapper-locations: classpath:mybatis/mapper/*.xml,classpath:mybatis/helperMapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
jasypt:
  encryptor:
    password: WwDih=dDq)
